import { CreditTx, Project, User } from "./types";

// Demo accounts — password is ignored by the fake auth, any value works.
export const SEED_USERS: User[] = [
  { id: "u1", name: "Asha Menon", email: "user@aqua.dev", role: "user", org: "Coastal Green Trust", walletBalance: 120 },
  { id: "v1", name: "Ravi Nair", email: "verifier@aqua.dev", role: "verifier", walletBalance: 0 },
  { id: "a1", name: "Priya Shah", email: "admin@aqua.dev", role: "admin", walletBalance: 0 },
];

export const SEED_PROJECTS: Project[] = [
  {
    id: "p1",
    orgName: "Coastal Green Trust",
    regNo: "CGT-2021-0091",
    year: "2021",
    fullName: "Asha Menon",
    email: "user@aqua.dev",
    mobile: "9876543210",
    designation: "Project Lead",
    address: "12 Marine Drive",
    state: "Kerala",
    district: "Ernakulam",
    pincode: "682001",
    title: "Vypin Mangrove Restoration",
    ecosystem: "Mangrove",
    plantationDate: "2024-08-12",
    area: "18",
    species: "Rhizophora mucronata",
    saplings: "9200",
    seedSource: "Local nursery",
    latitude: 10.05,
    longitude: 76.18,
    ownerId: "u1",
    status: "issued",
    listed: true,
    credits: 340,
    pricePerCredit: 9.5,
    verifierComment: "Healthy canopy, satellite match confirmed.",
    adminComment: "Approved for issuance.",
    createdAt: "2024-08-20",
  },
  {
    id: "p2",
    orgName: "BlueRoots Foundation",
    regNo: "BRF-2020-0442",
    year: "2020",
    fullName: "Asha Menon",
    email: "user@aqua.dev",
    mobile: "9876543210",
    designation: "Project Lead",
    address: "5 Backwater Rd",
    state: "Tamil Nadu",
    district: "Nagapattinam",
    pincode: "611001",
    title: "Pichavaram Seagrass Revival",
    ecosystem: "Seagrass",
    plantationDate: "2025-01-05",
    area: "9",
    species: "Halophila ovalis",
    saplings: "4100",
    seedSource: "Marine Biology Dept",
    latitude: 11.43,
    longitude: 79.79,
    ownerId: "u1",
    status: "verified",
    listed: false,
    credits: 0,
    pricePerCredit: 0,
    verifierComment: "Verified — passed to admin.",
    createdAt: "2025-01-18",
  },
  {
    id: "p3",
    orgName: "Coastal Green Trust",
    regNo: "CGT-2021-0091",
    year: "2021",
    fullName: "Asha Menon",
    email: "user@aqua.dev",
    mobile: "9876543210",
    designation: "Project Lead",
    address: "12 Marine Drive",
    state: "Gujarat",
    district: "Kutch",
    pincode: "370201",
    title: "Kutch Salt Marsh Project",
    ecosystem: "Salt marsh",
    plantationDate: "2025-05-22",
    area: "24",
    species: "Salicornia brachiata",
    saplings: "12000",
    seedSource: "Regional seed bank",
    latitude: 23.73,
    longitude: 70.15,
    ownerId: "u1",
    status: "pending",
    listed: false,
    credits: 0,
    pricePerCredit: 0,
    createdAt: "2025-06-01",
  },
  {
    id: "p4",
    orgName: "Sundarban Blue Collective",
    regNo: "SBC-2019-0777",
    year: "2019",
    fullName: "Dev Roy",
    email: "dev@sbc.dev",
    mobile: "9812340000",
    designation: "Field Coordinator",
    address: "Ganges Delta Block 4",
    state: "West Bengal",
    district: "South 24 Parganas",
    pincode: "743370",
    title: "Sundarban Mangrove Belt",
    ecosystem: "Mangrove",
    plantationDate: "2024-11-30",
    area: "40",
    species: "Avicennia marina",
    saplings: "21000",
    seedSource: "Community nursery",
    latitude: 21.94,
    longitude: 88.9,
    ownerId: "u9",
    status: "issued",
    listed: true,
    credits: 780,
    pricePerCredit: 11,
    verifierComment: "Excellent survival rate.",
    adminComment: "Issued.",
    createdAt: "2024-12-10",
  },
];

export const SEED_TX: CreditTx[] = [
  { id: "t1", type: "issued", projectTitle: "Vypin Mangrove Restoration", amount: 340, value: 0, date: "2024-08-25" },
  { id: "t2", type: "sell", projectTitle: "Vypin Mangrove Restoration", amount: 220, value: 2090, date: "2025-02-14" },
];
